create table employee
(
    id         bigint generated by default as identity,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    start_date date         not null,
    end_date   date,
    unique(email)
)